Major refactor of everything

diff --git a/bin/setup-pairup-server b/bin/setup-pairup-server
--- a/bin/setup-pairup-server
+++ b/bin/setup-pairup-server
@@ -10,47 +10,87 @@ set -e
 
 USAGE="Usage: ${0##*/} <ip-address> <pair-user-id> [<admin-user-id>]"
 
-die() { echo "$@" >&2; exit 1; }
+source "${BASH_SOURCE%/*}/helper-pairup-functions"
 
+# main() is called at bottom of this file:
 main() {
+  # "Global" variables we use:
   local root_user=root sudo=
-  local ip_address= admin_user= pair_user= setup_file_name=
+  local ip_address= admin_user= pair_user=
 
-  set -x
+  # Parse command line options:
   get-opts "$@"
+  # Make sure our runtime environment is ok:
   setup
-  set +x
-  build-config
-  [ -n "$PAIRUP_BUILD_ONLY" ] && exit
+
+  # XXX For now we run the test suite every time:
+  tests_ok ||
+    die "The pairup test suite is failing. You should look into that."
+
+  # Stage custom scripts in ./PairUp/
+  (
+    PairUp=./PairUp
+    build-config
+  )
+
+  # Exit if just testing ./PairUp/
+  if [ -n "$PAIRUP_BUILD_ONLY" ]; then
+    echo 'Build complete'
+    exit
+  fi
+
+  # Make script noisy now:
   set -x
 
-  root-setup
+  # Set up ssh key for root. May prompt for root password, depending on the
+  # server setup. This is the only time you need to enter the password. All
+  # pubkey afterwards:
+  if [ "$root_user" == root ]; then
+    cat "PairUp/user/$admin_user/id_rsa.pub" | ssh "$root_user@$ip_address" \
+      "cat > k; mkdir -p .ssh; chmod 700 .ssh; mv k .ssh/authorized_keys"
+  fi
+
+  # Copy PairUp dir over to root:
+  rsync -avz PairUp/ "$root_user@$ip_address:$PairUp"
+
   # Run the interactive root script:
-  ssh -t $root_user@$ip_address $sudo bash $setup_file_name
+  ssh -t "$root_user@$ip_address" $sudo bash "$PairUp/root-setup"
 
-  admin-setup
   # Run the interactive admin_user script:
-  ssh -t $admin_user@$ip_address bash $setup_file_name
+  ssh -t "$admin_user@$ip_address" bash "$PairUp/admin-setup" \
+    || true   # Show reconnect msg if the tmux fails
 
-  # Now you should be inside a perfectly working tmux session for pairing.
-  # Run the `PairInfo` command and it will tell you what your partner needs.
+  # \oXo/
+  # Now you should be inside a perfectly working tmux session for pairing!
+  # \oXo/
+
+  # Tell admin user how to reconnect when they leave tmux session:
+  cat PairUp/reconnect
 }
 
+# Parse command line args:
 get-opts() {
   local args=()
 
   for arg; do
     case "$arg" in
-    --hp)
+    -?|-h|--help)
+      echo "$Usage"
+      exit 0
+      ;;
+    --HP)                             # HPCloud (different root model)
       sudo=sudo
       root_user=ubuntu
       ;;
-    -N)
-      PAIRUP_NO_SUDO_PASSWORD=1
-      ;;
-    -B)
+    --BO)                             # Build Only (testing ./PairUp/)
       PAIRUP_BUILD_ONLY=1
-    *)    args+=("$arg") ;;
+      ;;
+    -*)
+      die "Unknown option: '$arg'"
+      ;;
+    *)
+      args+=("$arg")
+      ;;
     esac
   done
 
@@ -64,9 +104,9 @@ get-opts() {
   ip_address="$1"
   pair_user="$2"
   admin_user="${3:-$USER}"
-  setup_file_name="${0##*/}.bash"
 }
 
+# cd to the pairup repo directory:
 setup() {
   # cd to the pairup repo:
   pairup_bin="$0"
@@ -92,208 +132,58 @@ setup() {
   :
 }
 
-#------------------------------------------------------------------------------
-# Create local config build:
-#------------------------------------------------------------------------------
+# Copy everything the server will need into $PairUp/ and make sure both users
+# have a public key:
 build-config() {
   # Copy over default and user files:
-  rm -fr Build
-  cp -r conf Build
+  rm -fr $PairUp
+  cp -r conf $PairUp
+  cp -r bin $PairUp/
+  mkdir -p $PairUp/user
+  cp user/github-users* $PairUp/user/
 
+
+  # Take the default conf files and append the appropriate user conf files to
+  # each one:
   for user in "$admin_user" "$pair_user" private; do
-    for file in conf... github-repos known_hosts pre-install post-install ssh-config; do
+    for file in conf... cpan debian github install known_hosts ssh-config; do
       if [ -e "user/$user/$file" ]; then
-        cat "user/$user/$file" >> "Build/$file"
+        [ "$file" != known_hosts ] &&
+          echo -e "\n# $user settings:" >> "$PairUp/$file"
+        cat "user/$user/$file" >> "$PairUp/$file"
       fi
     done
+    [ "$user" == private ] && continue
+    mkdir -p "$PairUp/user/$user"
+    [ -d "user/$user" ] &&
+      cp -r user/"$user"/* "$PairUp/user/$user/"
+    assert-public-key
+  done
+
+  # Render the templates into $PairUp/
+  for t in template/*; do
+    text=$(< "$t")
+    text=${text//%%root_user%%/$root_user}
+    text=${text//%%admin_user%%/$admin_user}
+    text=${text//%%pair_user%%/$pair_user}
+    text=${text//%%pairup_repo%%/$pairup_repo}
+    text=${text//%%ip_address%%/$ip_address}
+    echo "$text" > "$PairUp/${t##*/}"
   done
 }
 
-#------------------------------------------------------------------------------
-# Do the 'root' stuff first:
-#------------------------------------------------------------------------------
-root-setup() {
-  # Set up ssh key for root. Needs root password:
-  admin_key=user/$admin_user/id_rsa.pub
-  if [ ! -e "$admin_key" ]; then
-    admin_key=~/.ssh/id_rsa.pub
-  fi
-  if [ -e "$admin_key" -a "$root_user" == root ]; then
-    cat "$admin_key" | ssh "$root_user@$ip_address" \
-      "cat > k; mkdir -p .ssh; chmod 700 .ssh; mv k .ssh/authorized_keys"
-  fi
-
-  # Copy Build dir over to root:
-  scp -r Build $root_user@$ip_address:
-
-  # Copy over pair's key if present:
-  pair_key="user/$pair_user/id_rsa.pub"
-  if [ -e "$pair_key" ]; then
-    scp "$pair_key" "$root_user@$ip_address:${pair_user}_key"
-  fi
-
-  # Copy this setup script to root's $HOME:
-  cat <<... | ssh $root_user@$ip_address "cat > $setup_file_name"
-#!/bin/bash
-
-continue?() {
-  set +x
-  echo -n "Error. ctl-c to exit. Enter to continue."
-  read
-  set -x
+# Use the rsa public key under ./user/$user/id_rsa.pub or attempt to get one
+# from GitHub, or error out:
+assert-public-key() {
+  [ -e "$PairUp/user/$user/id_rsa.pub" ] && return
+  github_user=`grep -Esh "^$user:" $PairUp/user/github-users* | head -n1 | cut -d: -f2`
+  github_user="${github_user:-$user}"
+  key="$( curl --silent "https://api.github.com/users/$github_user/keys" |
+    grep -E '^    "key": "ssh-rsa' | tail -n1 | cut -d'"' -f4
+  )"
+  [ -n "$key" ] || die "Can't find a public key for user '$user:$github_user'"
+  echo "$key" > "$PairUp/user/$user/id_rsa.pub"
 }
 
-set -ex
-
-# Remove this script:
-rm $setup_file_name
-
-# Add users. sudo for $admin_user:
-{
-  addgroup admin || continue?
-  adduser --gecos '' $admin_user || continue?
-  adduser $admin_user admin || continue?
-  :
-}
-
-# Move the public key over to $admin_user's home:
-{
-  mkdir -p /home/$admin_user/.ssh
-  chmod 700 /home/$admin_user/.ssh
-  cp ~/.ssh/authorized_keys /home/$admin_user/.ssh/
-  chown -R $admin_user:$admin_user /home/$admin_user/.ssh
-
-  if [ -n "$PAIRUP_NO_SUDO_PASSWORD" ]; then
-    echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
-  fi
-}
-
-# Add pair user:
-{
-  if [ -f ${pair_user}_key ]; then
-    adduser --disabled-password --gecos '' $pair_user || continue?
-    mkdir -p /home/$pair_user/.ssh
-    chmod 700 /home/$pair_user/.ssh
-    mv ${pair_user}_key /home/$pair_user/.ssh/authorized_keys
-    chown -R $pair_user:$pair_user /home/$pair_user/.ssh
-  else
-    adduser --gecos '' $pair_user || continue?
-  fi
-}
-
-# Copy known hosts to .ssh/:
-cp Build/known_hosts .ssh/known_hosts
-
-# Get git:
-{
-  apt-get update --yes
-  apt-get install git --yes || continue?
-
-  # Clone this repo, and put the tools in the PATH:
-  git clone $pairup_repo pairup || continue?
-
-  # Make a command called 'pairup' to (re)join tmux:
-  echo 'tmux -S /tmp/pairup attach || tmux -S /tmp/pairup' > /usr/local/bin/PairUp
-  chmod +x /usr/local/bin/PairUp
-
-  # apt-get install requested packages:
-  apt-get-install() {
-    for pkg; do
-      apt-get install --yes "\$pkg" || continue?
-    done
-  }
-
-  # Install requested software:
-  source Build/pre-install
-}
-
-# TODO scramble root password
-...
-}
-
-#------------------------------------------------------------------------------
-# Now do the 'admin_user' stuff:
-#------------------------------------------------------------------------------
-
-admin-setup() {
-  # Copy admin files to server:
-  {
-    # Copy over known_hosts and config to .ssh/:
-    scp Build/known_hosts $admin_user@$ip_address:.ssh/known_hosts
-    scp Build/ssh-config $admin_user@$ip_address:.ssh/config
-
-    # Copy Build dir over to $admin_user:
-    scp -r Build $admin_user@$ip_address:
-  }
-
-  # Copy this setup script to $admin_user's $HOME.
-  cat <<... | ssh $admin_user@$ip_address "cat > $setup_file_name"
-#!/bin/bash
-
-continue?() {
-  set +x
-  echo -n "Error. ctl-c to exit. Enter to continue."
-  read
-  set -x
-}
-
-set -ex
-
-# Remove this script:
-rm $setup_file_name
-
-# Get this repo remotely
-git clone $pairup_repo pairup || continue?
-
-# Get other repos of interest
-while read repo; do
-  [ -z "\$repo" ] && continue
-  [[ "\$repo" =~ ^\# ]] && continue
-  git clone git@github.com:\$repo src/\${repo#*/} || continue?
-  :
-done < Build/github-repos
-
-# Install ... dotfile management setup:
-# TODO move from ingydotnet to sharsaw
-git clone git@github.com:ingydotnet/....git || continue?
-mv Build/conf... .../conf
-.../... update
-.../... install
-
-# Make a little remote script called 'PairInfo'. Run this first thing to get
-# your bearings inside the VPS:
-cat <<.... > ~/bin/PairInfo
-chmod 777 /tmp/pairup
-
-# set -x
-# sudo bash Build/post-install &> /tmp/pairup-post-install.log &
-# set +x
-
-cat <<.....
-
-Welcome to your new PairUp VPS tmux session!
-
-Tell $pair_user to run this command:
-
-    ssh -t $pair_user@$ip_address PairUp
-
-.....
-....
-chmod +x ~/bin/PairInfo
-
-# Start tmux with a shared socket:
-tmux -S /tmp/pairup
-
-echo Reconnect to PairUp with:
-echo
-echo     ssh -t $ip_address PairUp
-echo
-
-# TODO - Figure out tmux startup script
-# - MOTD
-# - post-install
-# - Split screen, irssi
-...
-}
-
-main "$@"
+# Start the PairUp server setup:
+[ "$0" == "${BASH_SOURCE[0]}" ] && main "$@";:
