rename script to pairup
prompt on apt-get fails

diff --git a/conf/pre-install b/conf/pre-install
--- a/conf/pre-install
+++ b/conf/pre-install
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+apt-install-all() {
+  apt-get install --yes "${pkgs[@]}" || {
+    echo -c "Error. ctl-c to exit. Enter to continue."; read
+  }
+  :
+}
+
 # These packages are almost always needed for a PairUp:
 pkgs=(
   ack-grep
@@ -9,7 +16,7 @@ pkgs=(
   vim-nox
   weechat
 )
-apt-get install --yes "${pkgs[@]}"
+apt-install-all "${pkfs[@]}"
 
 # Symlink ack to ack-grep
 ln -fs /usr/bin/ack-grep /usr/local/bin/ack
